### ISSUE TITLE
Image carousels on about pages are broken

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pomegranate#441]
blocked by #448

<img width="991" alt="screenshot 2018-11-26 12 57 01" src="https://user-images.githubusercontent.com/784196/49035662-0f041f80-f17b-11e8-980b-7f680c4b2b0a.png">

**Comment by tpendragon** [comment]
This happened because we got rid of a bunch of plum images. I fixed all the home page ones by just re-selecting the right images in the edits for those carousels, but I guess I forgot the about pages.

**Comment by hackmastera** [comment]
I did the scheide collection without realizing an individual image needs to be selected. I emailed the curator to look over the update.

Here's how I've figured out how to identify which exact image to load:
in a dpul console, find the id of the collection via its slug. find the id of the about page via the collection_id. view the contents of the about page to get the iiif_manifest_url and iif_canvas_id.
In the figgy ui, look at the manifest (just replace 'plum' with 'figgy' in the manifest url) and ctrl-f to find the canvas_id (it's listed as a local_identifier). Click the link to download it; you'll need to know what it looks like in order to select it from the list of images.
