### ISSUE TITLE
I would like the Date sort for items in DPUL have the options of Ascending and Descending

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#621]
Curators have mentioned it would be helpful to have the Date sort options be both ascending and defending (and can be set as a default for viewing items in a collection/saved search/etc... Gutenberg items, for example, are attempting to tell a chronological story.

**Comment by tpendragon** [comment]
![Screen Shot 2019-10-01 at 10 41 29 AM](https://user-images.githubusercontent.com/2806645/65986102-0f72e400-e438-11e9-9fa1-ee5c3bab48fb.png)

**Comment by hackmastera** [comment]
This will require a data migration because the exhibits all save their configurations individually, so making the change in the catalog controller doesn't actually populate through all the exhibits.

Here's my plan.

1. Add new sort options `sort_date_desc` and `sort_date_asc`. Remove current `sort_date` option.
1. Run a rake task that iterates through every exhibit removing `sort_date` and adding in the new options.

This means exhibits won't have any date sort options in the short amount of time between deployment and completion of the rake task. @kelea99 is that acceptable? if not let me know and it's very easy to do it in 2 steps instead.
