### ISSUE TITLE
Viewer config not working in staging

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#624]
The staging viewer is trying to load config from:

https://figgy.princeton.edu/viewer/exhibit/config?manifest=https://figgy-staging.princeton.edu/concern/ephemera_folders/d4eee8ed-83e4-4bd9-aa5c-6f44e2f11ea4/manifest

**Comment by escowles** [comment]
Example of a broken object: https://dpul-staging.princeton.edu/sae/catalog/d4eee8ed-83e4-4bd9-aa5c-6f44e2f11ea4

**Comment by escowles** [comment]
This may only impact ephemera objects, since other objects are working, e.g., https://dpul-staging.princeton.edu/cotsen/catalog/rx913t88x

**Comment by tpendragon** [comment]
This is interesting. It's 404'ing building the dynamic config because it's asking Figgy to make it, when the manifest URL is from figgy-staging. I could switch it, but all it would do is break the other case.

**Comment by escowles** [comment]
I don't understand why the non-ephemera objects have working viewers.  Is there something different about how they are setup?  Or is the fix here to just make dpul-staging use the viewer from figgy-staging?

**Comment by tpendragon** [comment]
It's not ephemera/non-ephemera. That second example is a manifest from when staging was pointed at production Figgy. Its URL is https://figgy.princeton.edu/concern/scanned_resources/8fbeac06-bd62-4be4-be2a-070776bc2db4/manifest

**Comment by tpendragon** [comment]
What's happening:

DPUL's viewer is requesting a config from Figgy using the following URL: https://figgy.princeton.edu/viewer/exhibit/config?manifest=https://figgy-staging.princeton.edu/concern/ephemera_folders/d4eee8ed-83e4-4bd9-aa5c-6f44e2f11ea4/manifest

It does this because the config needs to be dynamic so it can hide the download button if someone can't download things from that resource. The URL it uses to build that config is configurable. However, if a system has both figgy staging and production items, then for one of those it will be asking for a non-existent resource and so that config will 404, causing the viewer to not load.
