### ISSUE TITLE
Two items records in figgy with the same identifier are not showing up as individual item records or in two viewers within the same item record in DPUL

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#788]
not sure if this is. a bug. or an enhancement request, @hackmastera. This was brought to my attention this morning by Eric White, the curator of the exhibit. 

Figgy item records: https://figgy.princeton.edu/catalog?utf8=✓&q=4601808

How they display in online catalog (2 viewers in 1 item record): https://catalog.princeton.edu/catalog/4601808#view

How they/it shows up in DPUL (item record): https://dpul.princeton.edu/gutenberg/catalog/zw12z537v
DPUL list for 4601808: https://dpul.princeton.edu/gutenberg/catalog/zw12z537v

Action:
I add these 2 figgy records to the "Germany Grouping" collection, and sync that collection to dpul. They have the same source metadata identifier.

Expected/desired outcome:
Both records are synced to the dpul exhibit and each one can be viewed with its correct iiif object.

Actual outcome:
Only one of them syncs to the dpul exhibit: https://dpul.princeton.edu/gutenberg/catalog/zw12z537v.
@kelea99 has tried things and believes it's the most recently updated one that gets published.

**Comment by hackmastera** [comment]
The 2 objects have the same ark. Is there another use case that requires them to have the same ark?

@escowles Do you know?

**Comment by escowles** [comment]
@hackmastera The two items should definitely have different ARKs. I think they both have the same ARK because their is only one in the MARC record. So I think we should update the fragment (https://figgy.princeton.edu/catalog/29a70eaa-5e27-4501-9932-5321c383fc61) to have a new ARK, and then it will stop conflicting with the other object.

**Comment by kelea99** [comment]
thank you, @escowles ! @hackmastera can we do this next week for Eric real quick? it sounds small and like an easy ticket to close?

**Comment by hackmastera** [comment]
Make a new ark manually for the fragment using the web form at http://ezid.cdlib.org/  -- don't fill in metadata because figgy will do that once the ark is saved. Then replace the ark for this record in figgy.

Once the identifier has been set locally on the record it won't show the one from upstream.

**Comment by hackmastera** [comment]
@kelea99 can you take a look now? The fragment got a new ark and I see it on dpul at https://dpul.princeton.edu/gutenberg/catalog/c247f117j; old one is still at https://dpul.princeton.edu/gutenberg/catalog/zw12z537v

You still see the old ark under "imported metadata" for the fragment record in figgy, but the actual / new ark is lower down on the show page.

**Comment by kelea99** [comment]
yup! looks good, @hackmastera . both showing up. Ill do the title override and description now.  Thank you so much!
