### ISSUE TITLE
5k+ Western Americana (WC064) items not indexing in DPUL collection

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#793]
Items are complete in figgy but not showing up in DPUL.

Examples:
* https://figgy.princeton.edu/catalog/a9044f8a-ec64-4d38-9141-435d5c8c650b
* https://figgy.princeton.edu/catalog/278946cd-4198-4bbd-8dc0-652fc706f15a

DPUL exhibit:
* https://dpul.princeton.edu/pudl0017

These need be live June 10th.

**Comment by hackmastera** [comment]
The error queue definitely does not have this many items in it, and the sample items given are not in the queue. So it doesn't look like this is a rabbitmq issue. I'll update the description with the links.

**Comment by hackmastera** [comment]
Update: For resources with finding aid source_metadata_ids, figgy's jsonld has a nested collection object. when indexing into solr pomegranate thinks this is a child document, which it's not set up to handle. This appears to be the source of the problem here. Still need to do some more analysis on what jsonld should look like.
