### ISSUE TITLE
Duplicate database entries for custom field override-title_ssim

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#828]
https://dpul.princeton.edu/eastasian

**Comment by hackmastera** [comment]
The exhibit has 6676 custom fields called `override-title_ssim`. Looks like #731.

**Comment by hackmastera** [comment]
I deleted the duplicates for now. I didn't do anything to any other exhibits. Here are the duplicate counts:

```
Spotlight::CustomField.all.select{|v| v.slug.length > 30}.map(&:exhibit_id).group_by{|i| i}.map{|k,v| [Spotlight::Exhibit.find(k).slug, v.count]}
=> [["cotsen", 615], ["hellenica", 194], ["music", 494], ["eastasian", 97], ["lapidus", 315], ["pudl0135", 256], ["scheide", 206], ["neareast", 92], ["pudl0058", 38], ["papyri", 337], ["Fragments", 9], ["ealtoc", 1]]
```

**Comment by tpendragon** [comment]
We noticed it was true for Alternative in one collection too, but it's definitely a huge issue for Override Title. We're likely doing something wrong for that field, since we create it ourselves at index time.

**Comment by tpendragon** [comment]
We think https://github.com/pulibrary/pomegranate/blob/master/spec/models/iiif_resource_spec.rb#L134-L149 tests the fact that new custom fields aren't created on every index. It must be creating override title custom fields elsewhere? We've also noticed some exhibits have multiple override title custom fields.

**Comment by tpendragon** [comment]
We think the problem is that https://github.com/pulibrary/pomegranate/blob/ac6b8680cdc897cad6c040e53af7243349f15ebc/app/services/iiif_manifest.rb#L144

uses `exhibit_custom_fields`, which is a hash of all the CustomFields for an exhibit by label. Unfortunately for some exhibits there are somehow two CustomFields with the same label, but different slugs, so the hash's value is overridden. Changing this to use `exhibit.custom_fields.pluck(:slug)` should fix that and be covered by existing tests.

We don't know how the `Spotlight::CustomField` with the slug `override-title_ssim` is created.

**Comment by hackmastera** [comment]
Final thoughts here: 

from @tpendragon: "I think the issue was the custom fields make two override titles when reindexing happens across multiple threads, then if the most recent one that got created has a weird slug that issue we found happens."

Regarding how the slug was created to begin with, this "slug candidate" functionality in friendly_id seems relevant. here's some documentation in case we need it down the line:

- http://norman.github.io/friendly_id/5.0/
- https://github.com/norman/friendly_id/blob/e9a591b09c70e788fb35a7f45c5e146e94355f2c/lib/friendly_id/slugged.rb

It's being set up here in spotlight: https://github.com/projectblacklight/spotlight/blob/e7060283bd8b7478bc74f4dcfcf6bed72e6aa3f0/app/models/spotlight/custom_field.rb#L101
